#!/bin/bash

server=paraulata.casa.vm
user=jorge
mount_point=/media

drives=$(ssh $user@$server ls $mount_point )

for dir in ${drives[@]}; do
	mkdir $mount/$dir;
	chown jorge $mount/$dir
	sshfs jorge@paraulata.casa.vm:$mount/$dir $mount/$dir &
done
